apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-buy-deployment
  labels:
    app: good-buy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: good-buy
  template:
    metadata:
      labels:
        app: good-buy
    spec:
      containers:
      - name: good-buy
        image: kandwalshantanu/goodbuy:0.0.4.RELEASE
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: good-buy-service
  labels:
    app: good-buy
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: good-buy
