apiVersion: v1
kind: Service
metadata:
  name: good-buy-service
  labels:
    app: good-buy
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: good-buy
